---
- name: Download tarball
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local/src/go
    checksum: "{{ go_checksum }}"

- name: Prepare install directory
  shell: "mkdir -p {{ go_install_dir }}"

- name: Extract tarball
  unarchive:
    src: /usr/local/src/go
    dest: "{{ go_install_dir }}"
    copy: no

- name: Prepare working directories
  shell: "mkdir -p {{ go_source_dir }}/{src,pkg,bin}"

- name: Add the go bin directory to PATH for all users
  copy:
    src: go-bin.sh
    dest: /etc/profile.d

- name: Set GOPATH for all users
  copy:
    src: go-path.sh
    dest: /etc/profile.d

- name: Check that golang is installed
  shell: command -v go env >/dev/null 2>&1
  register: is_go_installed
  ignore_errors: false