---
- name: Get Nodesource GPG key
  shell: "curl -sL https://deb.nodesource.com/setup_{{ nodejs_version}}.x | sudo -E bash -"
  become: true

- name: Install Node.js
  apt:
      name: nodejs
      update_cache: true

- name: Get YARN GPG Key
  shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
  become: true

- name: Add YARN to package sources
  shell: "echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list"
  become: true

- name: Install YARN
  apt:
      name: yarn
      update_cache: true

- name: Install NVM
  shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash"
  become: true
