---
- name: Install Python3
  apt: name="{{ item }}" state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3
    - python3-dev
    - python3-pip
    - python3-venv

- name: Upgrade pip
  shell: pip install --upgrade pip
  become: false

- name: Copy global requirements file
  copy:
    src: requirements-global.txt
    dest: "{{ python_global_req_file }}"
    state: present

- name: Install global requirements
  shell: "pip install -r {{ python_global_req_file }}"
  become: false

- name: Install pyenv
  shell: "git clone https://github.com/pyenv/pyenv.git {{ python_pyenv_loc }}"
  become: false