---
- name: Update
  apt:
    update_cache: true

- name: Install base packages
  apt: name="{{item}}" state=present
  with_items:
      - curl
      - tree
      - zsh
      - build-essential
      
  ignore_errors: yes

- name: Install dev tools
  apt: name="{{item}}" state=present
  with_items:
      - make
      - git
  ignore_errors: yes

#- include: vim.yaml
#- include: dropbox.yaml
#- include: r.yaml
